name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2, 3.3]
    env:
      CC_TEST_REPORTER_ID: 1670b97bb8c09d4f4bad81e559f41c7588641c67bd700c933c267bbe7dbbef7f
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
